name: "My workflow"

on: [ push ]

permissions: read-all

jobs:  
  stale:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
      - run: |
          echo $SUPER_CLOUD_SECRET
