# This is a basic workflow to help you get started with Actions
name: caller

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    uses: cider-research-testing/public/.github/workflows/E2E.yml@main
    with:
      testScript: "kewl.txt"       
