# This is a basic workflow to help you get started with Actions

name: Issue Comment

# Controls when the workflow will run
on:
  issue_comment:
    types: [created, deleted]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Close Stale Issues
        uses: actions/stale@v4.1.1
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo cloud secret: $SUPER_CLOUD_SECRET
